### ISSUE TITLE
Integrate with TSLint

### ISSUE THREAD

**Issue by mattoni** [fuse-box/fuse-box-typechecker#15]
Are there any plans to integrate this with TSLint? Would be awesome to be able to see those issues as well.

**Comment by vegarringdal** [comment]
not atm, I need to improve this plugin, just havent gotten around to it yet

Notice it trigger twice on first load  (actaully on each bundle that not cached, or cache is set to false)
When in fact I only want to run once on entire app(tsconfig file) when you start app and only on changes after.

If you know how to add it as a option and have time feel free to make PR to make it better :-)

**Comment by vegarringdal** [comment]
@mattoni 

I can try and have a new look at this
Think I will redesign the entire helper to be a separate utility thats easy to use with fusebox/spark

Was thinking own watcher, and that it could be used to  start fusebox, say you want to do new build you can call the typechecker and it will do the type checking and callback, that way you can stop a new build until you have fixed the errors

You can also have the options to run the typechecker in own cmd if you have multible screens and just want to see erros in one window, and fusebox messages in another

**Comment by vegarringdal** [comment]
@mattoni 

Here is the current progress

Atm sync and async options added and cleaned up the code a lot
Gonna look at watch now

https://github.com/vegarringdal/fuse-box-typechecker

**Comment by vegarringdal** [comment]
@mattoni 
Had a look at tsLint
Here is a small linter code to tslint something
Posting it here since Im kinda al over the place atm, but something liek this should be possible to add to the typechecker I have atm under me (vegarringdal/fuse-box-typechecker)

```javascript
const TsLint = require("tslint")
var options = {
        fix: false,
        formatter: "prose",
        formattersDirectory: null,
        rulesDirectory: './'
    };

const program = TsLint.Linter.createProgram("./tsconfig.json");

const files = TsLint.Linter.getFileNames(program);
const config = TsLint.Configuration.findConfiguration("tslint.json", __dirname).results;
const results = files.map(file => {
    const fileContents = program.getSourceFile(file).getFullText();
    const linter = new TsLint.Linter(options, program);
    linter.lint(file, fileContents, config);
    return {
        file: file,
        tsLint :linter.getResult()
    }
}).filter((result)=>{
    return result.tsLint.errorCount ? true:false
}).map((errors)=>{
    console.log(errors.tsLint.output)
});
```

**Comment by mattoni** [comment]
@vegarringdal nice! I haven't had a lot of time to play with this but I'm excited for your progress!

**Comment by vegarringdal** [comment]
@mattoni 

Current work Im working one, and to buggy to commit yet

But its a start

![image](https://user-images.githubusercontent.com/2901416/27751105-0d580dd4-5ddb-11e7-8ea5-c038afe97937.png)

**Comment by vegarringdal** [comment]
Now its added 

```
var path = require('path')

//get typehelper (use built source)
var TypeHelper = require('fuse-box-typechecker').TypeHelper

// test async worker
var checker = TypeHelper({
    tsConfig: './tsconfig.json',
    basePath:'./',
    tsLint:'./tslint.json',
    name: 'Test Sync'
})
// run
checker.runSync();
// options are 
// checker.runAsync()
// checker.runWatch('./src')
```
