### ISSUE TITLE
Format errors to allow vscode to take you to proper line

### ISSUE THREAD

**Issue by mattoni** [fuse-box/fuse-box-typechecker#20]
When there is an error, typechecker outputs:
`views/signup/email-verify/EmailVerifyForm.tsx: (57:36)`, which in vscode if you ctrl+click to the file, it takes you to the top instead of to line 57:36. I believe you need to format it so that you have the line number not in parenthesis and after the colon. Would make it that much better :)

**Comment by vegarringdal** [comment]
VERY NICE!
I didnt know about this :-)
Just tested replacing `:` with `,` and contr-click works like a charm
Will fix this tomorrow

**Comment by vegarringdal** [comment]
fixed
