### ISSUE TITLE
Allow tslint errors to be warnings instead of errors

### ISSUE THREAD

**Issue by mattoni** [fuse-box/fuse-box-typechecker#21]
Would be nice to customize what type of output each error class has. For example, tslint errors could be set to "warning" and come up as yellow, without failing on sync

**Comment by vegarringdal** [comment]
> Would be nice to customize what type of output each error class has. For example, tslint errors could be set to "warning" and come up as yellow, 

So option to have yellow color for lint issues then ?
But point is that you want to get rid of it, isnt it, beeing strick usually brings better code..


> without failing on sync

Failing ? does it throw error?
If so please post a picture or something

**Comment by mattoni** [comment]
Sorry I thought this would exit the program if it ran into errors so that it doesn't continue building. I have it in my fuse file like so:

```
Sparky.task("run", async () => {
    if (envVars.NODE_ENV === "production") {
        typeChecker.runSync();
    } else {
        typeChecker.runWatch('./src');
    }

    producer = await buildVars.fuse!.run();
});
```
It would be nice if 
1) it exits the program if there is an error 
2) allow for warnings on certain types, so it wont exit if there are only warnings

**Comment by vegarringdal** [comment]
@mattoni 

I still have the throw options you use same place you set base path etc
Even added one for tsLint if you want to go crazy
```
throwOnSyntactic?: boolean;
throwOnSemantic?: boolean;
throwOnTsLint?:  boolean;
throwOnGlobal?: boolean;
throwOnOptions?: boolean;
```

**Comment by mattoni** [comment]
Gotcha, forgot those were there. Thanks! Maybe add some color differences for ones that don't throw, but this works for now.

**Comment by vegarringdal** [comment]
Ill add a optn for yellow collor for the lint
Dunno if I know type of error when its looping them, I might need to find a map or soemthing to have same options for the others

![image](https://user-images.githubusercontent.com/2901416/27761473-9d2b0f5c-5e5c-11e7-84fb-cd73c6fe7617.png)

**Comment by vegarringdal** [comment]
@mattoni 

added these options 👍 

```
    yellowLint?: boolean; // use yellow color instead of red on TSLint errors
    yellowOnOptions?: boolean; // use yellow color instead of red on Options errors
    yellowOnGlobal?: boolean; // use yellow color instead of red on Global errors
    yellowOnSemantic?: boolean; // use yellow color instead of red on Semantic errors
    yellowOnSyntactic?: boolean; // use yellow color instead of red on Syntactic errors
```

**Comment by vegarringdal** [comment]
@mattoni 
Did the color options work out ?
