### ISSUE TITLE
Allow js files to also be linted?

### ISSUE THREAD

**Issue by pyros2097** [fuse-box/fuse-box-typechecker#35]
Right now I'm using typescript option to compile my js files. I want to be able to use tslint for linting my js code so that I don't need to rely on eslint, babel and other stuff. Also this might be faster.
Is there any way to do this?
I heard tslint itself allows to do this.
https://github.com/palantir/tslint/issues/515

**Comment by vegarringdal** [comment]
Dunno atm, tried to read a little bit in the thread/link you posted

Have you tried adding jsRules to the tslint.json file?
Something like this:
https://github.com/ilkka/tslint-js-test/blob/master/tslint.json

And allowJs in tsconfig.json ?

**Comment by pyros2097** [comment]
It seems type check doesn't even go through my js files for some reason. So i created a ts file and imported and that also doesn't seem to be detected. That could be the reason.
Anyway here is the file if need be.
https://github.com/pyros2097/cress-example/blob/master/fuse.js
```

Typechecker plugin(syns) :App typechecker.
Time:Wed Nov 01 2017 19:49:05 GMT+0530 (IST) 

File errors:
└── ./node_modules/@types/graphql/subscription/subscribe.d.ts
   | /home/pyros2097/Code/mine/cress-example/node_modules/@types/graphql/subscription/subscribe.d.ts (17,4) (Error:TS2304) Cannot find name 'AsyncIterator'.
   | /home/pyros2097/Code/mine/cress-example/node_modules/@types/graphql/subscription/subscribe.d.ts (29,4) (Error:TS2304) Cannot find name 'AsyncIterable'.

Errors:2
└── Options: 0
└── Global: 0
└── Syntactic: 0
└── Semantic: 2
└── TsLint: 0

Typechecking time: 1444ms
Quiting typechecker

[HPM] Proxy created: /  ->  http://localhost:3000

-----------------------------------------------------------------
Development server running http://localhost:4000 @ 2.4.0
-----------------------------------------------------------------

19:49:06: HMR is enabled
19:49:08: Client connected
19:49:10: Connection closed
19:49:10: Client connected
```

**Comment by pyros2097** [comment]
Oops.. It works my bad.
it seems my tsconfig was configured wrong.
```
 "include": [
    "./app/**/*"
  ]
```
My source was in app not src. Thats the problem. Its working properly now. Thanks. :+1:
