### ISSUE TITLE
Make dependency to es7 `Object.entries` explicit or provide a polyfill

### ISSUE THREAD

**Issue by sveinburne** [fuse-box/fuse-box-typechecker#37]
As can be seen [on this table](http://node.green/#ES2017), Node 6.X doesn't support `Object.entries` without the use of `--harmony` flag.
You are using [this es7 feature here](https://github.com/fuse-box/fuse-box-typechecker/blob/master/src/checker.ts#L171).

Since fusebox [explicitly rely on nodejs 6.9.5+](https://github.com/fuse-box/fuse-box/blob/master/package.json), I would recommend providing a polyfill for those in my situation using latest 6.X versions.

![image](https://user-images.githubusercontent.com/3646758/32281658-dde673c0-bef5-11e7-9031-dee5ecf169f2.png)

[This little library offer a basic shim](https://github.com/es-shims/Object.entries)

```javascript
var entries = require('object.entries');


if (!Object.entries) {
	entries.shim();
}
```

**Comment by vegarringdal** [comment]
Thx, though I was targeting es5 when it was transpiled, and stuff liek this would be just fixed.
Maybe Ive messed up something , if you see what Ive done wrong then please send a PR if you have nodejs  6 installed to test with.
If not Ill try and look at it in the weekend if I have time

**Comment by sveinburne** [comment]
@vegarringdal I found the reason after some research. Typescript compiler provide only few polyfills by default. So when you `target: es5`, you target the syntax, not the js API.

That can be seen [in this feature table](http://kangax.github.io/compat-table/es2016plus/) where Typescript + **core-js** columns suggests the polyfills are shipped with the latter. 
So your build logic should include those corejs polyfills !

However I am not familiar with gulp ; but my pull request offers a quick fix for `Object.entries`.
