### ISSUE TITLE
Add option to exclude files/folder

### ISSUE THREAD

**Issue by John0x** [fuse-box/fuse-box-typechecker#40]
Hey, there is no option to exclude files or folders, even though the tslint cli supports it.

**Comment by vegarringdal** [comment]
Hi have you tried to use the tsconfig.json to exclude files ?

**Comment by vegarringdal** [comment]
@John0x Did you try and exclude files/folders in tsconfig.json?

**Comment by John0x** [comment]
Ah, sorry, the problem was caused by something else :)
Closing now
