### ISSUE TITLE
Type checker exits with 0 even when error is thrown

### ISSUE THREAD

**Issue by mattoni** [fuse-box/fuse-box-typechecker#42]
Not sure if you noticed this, but I'm trying to get the typechecker to stop my Docker container from building on a type error. I have it set to sync and throw on error. It successfully stops the build but the process is exiting with a 0 exit code instead of a 1, causing docker to think it was successful and continuing the build.

Would you be able to make it so the error code is propagated properly? Thanks!

**Comment by vegarringdal** [comment]
Will have a look at it tonight/tomorrow.
Remind me if I dont respond by tomorrow :-)
Prb dumb mistake we made after some of features we added with callback :-)
Thanks for reporting the error. 

Guessing the mistakes are somewhere here, if you try look at it
https://github.com/fuse-box/fuse-box-typechecker/blob/master/src/checker.ts#L311-L323
https://github.com/fuse-box/fuse-box-typechecker/blob/master/src/index.ts#L273-L286

**Comment by vegarringdal** [comment]
@mattoni 
Can you do a test for me, does this exit with correct code?

```js
let checkerAsync = TypeHelper({
        tsConfig: './tsconfig.json',
        basePath: './',
        tsLint: './tslint.json',
        name: 'checkerAsync',
        throwOnTsLint: true
    });
    checkerAsync.runAsync((err)=>{
        // I will not run if error is thrown....
        console.log('\nErrors async run:'+ err)
    })
```

**Comment by vegarringdal** [comment]
@mattoni fix bug on sync, updated to 2.6.4 and publish new version on npm.
Please confirm this fixed the issue.

**Comment by vegarringdal** [comment]
How I tested:

- removed a semicolon, then ran this code..

```js

process.on('exit', (code) => {
    console.log(`About to exit with code: ${code}`);
});


var TypeHelper = require('./dist/commonjs/index.js').TypeHelper

  let checkerSync = TypeHelper({
    tsConfig: './tsconfig.json',
    basePath: './',
    tsLint: './tslint.json',
    name: 'checkerSync',
    throwOnTsLint: true
});
checkerSync.runSync()
```

**Comment by mattoni** [comment]
@vegarringdal seems to have fixed it, thanks!

**Comment by vegarringdal** [comment]
Great, I had a throw int here before, but exit with code 1 is cleaner
