### ISSUE TITLE
Remove TSlint requirement

### ISSUE THREAD

**Issue by Fconstant** [fuse-box/fuse-box-typechecker#48]
I don't use TSLint at all, but this tool gives me an error if I don't install tslint as a dependency to my project.

TSlint should be optional.

**Comment by vegarringdal** [comment]
will have a look into it
only reason why Ive never included typescript or tslint as requirement was to not force any versions on user.

any reason why you dont want to lint, it would only be a dev dependency..

**Comment by vegarringdal** [comment]
thx for PR, updated to v 2.8.0 and npm
