### ISSUE TITLE
Run during fuse build

### ISSUE THREAD

**Issue by mitsoe** [fuse-box/fuse-box-typechecker#5]
Before bundling run the typescript checker and fail if it contains typescript errors.

**Comment by vegarringdal** [comment]
@nchanged 
Is there any way I can stop a bundling during first run and when updates happend ?

**Comment by nchanged** [comment]
`throw "wut"` =)

**Comment by nchanged** [comment]
but we need to have a mechanism to do it properly, i agree

**Comment by vegarringdal** [comment]
this is possible now, just run it in sync mode and use the throw error options
