### ISSUE TITLE
Option to pipe errors to a file

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box-typechecker#50]
I'm implementing continuous integration, would be nice if there was an easy way to pipe the output to a file instead of stdout.

Bonus if I could have the file either not be created, or just say 'success' in the event zero errors are generated. Ideas?

**Comment by vegarringdal** [comment]
Could maybe have a option to return whats printed to console, so you could save it.
Then user could save it how he wanted it.
Is the console print a issue ?
I havent worked much with continuous integration

**Comment by jpike88** [comment]
Never mind, not necessary. Just noticed that throw flags in the config (btw I think you do a spellcheck, the word ‘throwe’ I see used)

**Comment by vegarringdal** [comment]
ok, Ill have a look at those typos
