### ISSUE TITLE
next - 2.10.0-next.X

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box-typechecker#52]
Figured I could have a thread on what will be and is in `next` version

`fuse-box-typechecker@next`

### Gulp removed (next.1)
its using fusebox 2.9.0 to make own dist

### runSilentSync() (next.4)

Returns object, and does not print any errors to console.
if no check have been preformed it returns undefined

``` js
let checkerSync = TypeHelper({
        tsConfig: './tsconfig.json',
        basePath: './',
        tsLint: './tslint.json',
        name: 'returnResultObj'
    });
    const resultObj = checkerSync.runSilentSync();
    console.log(resultObj);
```
result without errors
![image](https://user-images.githubusercontent.com/2901416/40884852-b55d3cc6-671b-11e8-84c5-5b6615d0ae85.png)

one with 2 simple errors
![image](https://user-images.githubusercontent.com/2901416/40884854-bab0904c-671b-11e8-8a73-b2bd520a0da0.png)

This will display the default paths to settings and name..
![image](https://user-images.githubusercontent.com/2901416/40884875-01670f16-671c-11e8-9f47-a4d742440e8c.png)

### runSilentPromise() (next 4)
// same as above, just own thread with promise

```
var TypeHelper = require('./dist/commonjs/index.js').TypeHelper

let checkerSync = TypeHelper({
    tsConfig: './tsconfig.json',
    basePath: './',
    tsLint: './tslint.json',
    name: 'checkerPromise'
});


checkerSync.runSilentPromise().then((results) => {
    console.log(results)
})

```

### checkerWatch.runWatch('./src', callback) (next.6)

added option for callback
* returns 'edit' on removed file and changed
* returns 'updated' + errors when done

might get some small edits

### skipTsErrors?: number[];// skip ts errors  (next.7)
* option to skip tsErrors

**Comment by dlannoye** [comment]
So I did some digging in the code and I think this would work, but looking at the code I think it might work better to just return the objects you are using in printResults. I am thinking that the results object could be an object with the following interface:
```
{
   lintErrorMessages?: ITSLintError[];
   tsErrorMessages?: ITSError[];
}
```

These should be pretty straightforward to serialized compared to the full Diagnostics that typescript returns, but also have enough information for scenarios like mine where I want to re-log the errors to a different log.

What do you think of this interface? If you like it I would be willing to refactor to having this for the `Obj` versions of the check api.

**Comment by vegarringdal** [comment]
@dlannoye 
fuse-box-typechecker@2.10.0-next.3

```js
var path = require('path')

//get typehelper (use built source)
var TypeHelper = require('./dist/commonjs/index.js').TypeHelper

// sync run
let checkerSync = TypeHelper({
    tsConfig: './tsconfig.json',
    basePath: './',
    tsLint: './tslint.json',
    name: 'checkerPromiseAndreturnObj'
});


checkerSync.checkSyncReturnObjPromise().then((results) => {
    console.log(results)
})
```

you can give it a try
should try and reproduce option and global errors so we could test if they make it fail, but I didnt manage to make then 😂

**Comment by dlannoye** [comment]
For naming are you stuck on `checkSyncReturnObj` and `checkSyncReturnObjPromise` to me something like `checkSilentSync`, `checkSilentPromise` and `checkSilentAsync` would be nice to go with the current `runPromise`, `runSync` and `runAsync` apis and indicate that they don't print the results. Also, if you are interested in a bigger change you could move away form the worker doing the printing and have the run* versions of the api just call the checkSilent version and then use the result and doing printing there.

**Comment by vegarringdal** [comment]
@dlannoye 
Hi renaming to `runSilentSync` and `runSilentPromise ` sounds like a great idea.
Main reason why Im using the `next.x` now it to be able to do small changes without bringing breaking change :-)

> you could move away form the worker doing the printing

no, need to worker to be able to do printing to console, I usually use this when working on a project using fusebox, on the bundle start I call `startTreadAndWait()` and then on fusebox `complete` bundle event I call the `useThreadAndTypecheck()`. Since its doing all work in thread the dev server wont be halted on every bundle update on saves.

Regarding breaking changes, figured we could make what we have stable, try and test if there is a breaking bug ( do you know how to reproduce ts option errors and global ? ). Then we can release and start a new thread about 3.0.0, here we could rename a lot etc, just need to make sure and make a guide how to upgrade so its easy for people

**Comment by vegarringdal** [comment]
I can rename the functions later today

**Comment by vegarringdal** [comment]
@dlannoye 
fuse-box-typechecker@2.10.0-next.4 published, now they are called ```runSilentSync``` and ```runSilentPromise```

**Comment by vegarringdal** [comment]
@dlannoye 
Did you get a chance to test `?
I really need to figure out how to produce a global and a option errors to make sure it works

**Comment by dlannoye** [comment]
I haven't got a good chance to test it yet. I did do some digging to see if I could produce a global or an option error, but didn't find anything there yet.

**Comment by vegarringdal** [comment]
@dlannoye 

OK, I'll hold back the release of **v2.10.0** until you get a chance to test. 
This way we dont miss a silly mistake :-)

I will hopefully managed to start on some better tests, just need to find out how far I want to take v3.0.0

**Comment by vegarringdal** [comment]
@dlannoye 

Gotten chance to try it?
Most important part is that you have not noticed any bugs
Also added option to skip tsErrors due to #53 
`skipTsErrors?: number[];// skip ts errors`

**Comment by dlannoye** [comment]
I tried fuse-box-typechecker@2.10.0-next.7 against several of my projects
and everything looked good for them.

**Comment by vegarringdal** [comment]
Great, Ill prb release it during the weekend then.

**Comment by vegarringdal** [comment]
@dlannoye @jpike88 

version fuse-box-typechecker@2.10.0 released

https://github.com/fuse-box/fuse-box-typechecker/releases/tag/2.10.0
