### ISSUE TITLE
resolveJsonModule not working

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box-typechecker#53]
I get this error when turning on resolveJsonModule:

/Users/Me/Project/angularHelpers.ts (4,26) (Error:TS2307) Cannot find module './en-AU.json'

Can you confirm whether resolveJsonModule works for you at all?

Using TS 2.9.1, VSCode actually reports it as fine, and tsc has a weirder issue going on:

https://github.com/Microsoft/TypeScript/issues/24743

**UPDATE: the weirder issue seems to be deliberate...** 

https://github.com/Microsoft/TypeScript/issues/24715

Thanks

**Comment by vegarringdal** [comment]
Sample
https://github.com/vegarringdal/toDelete

![image](https://user-images.githubusercontent.com/2901416/41106443-52de96a0-6a70-11e8-9df2-9c0de7a9ba43.png)


option error goes away if I add the outDir

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "outDir": "",
    "resolveJsonModule": true,
    "esModuleInterop": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by vegarringdal** [comment]
Update, tried to read more about this
It says here it will try and copy over the to files to output, so warning is kinda correct... maybe

![image](https://user-images.githubusercontent.com/2901416/41107276-5734643a-6a72-11e8-96db-55c64ec7d1b9.png)

**Comment by vegarringdal** [comment]
@jpike88 
How did this turn out ?

**Comment by jpike88** [comment]
I think we should build in exemptions to omit this error. The problem is that outDir shouldn't need a value for this to do its job, which is just to check types. Files being written/not written shouldn't be a factor here.

**Comment by vegarringdal** [comment]
yes, we could add a option to skip ts errors, as a option.

**Comment by vegarringdal** [comment]
@jpike88 
`skipTsErrors?: number[];// skip ts errors` to options

Can test it here:
fuse-box-typechecker@2.10.0-next.7

Tell me how it works out for you

**Comment by jpike88** [comment]
this solves the issue. eagerly awaiting release :D
