### ISSUE TITLE
Replacing chalk with in-house solution makes output impossible to print

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box-typechecker#66]
If I use getResult, I get an output containing useful output, routing that to console.log just means I see all these color tags (e.g. ```<cyan>```) that are impossible to reinterpret.

Can the logger be exposed to strip/convert the colours back into terminal compatible output?

**Comment by vegarringdal** [comment]
Well there is a reason why I asked if this was what you wanted before I published it. 😄 

You should be able to get it if you want it like this without me doing anything
const pluginTypeChecker = require("fuse-box-typechecker/dist/fuseLogger/fuseLog").FuseLog;

**Comment by vegarringdal** [comment]
Have a look at this one:
https://github.com/fuse-box/fuse-box-typechecker/blob/master/src/printResult.ts#L123

**Comment by jpike88** [comment]
I imported the FuseLog class directly, that's created a good enough solution. Thanks!!
