### ISSUE TITLE
Support fuse-box 1.4.1

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box-typechecker#9]
Support fuse-box 1.4.1

Started work here on my "test" branch
https://github.com/vegarringdal/fuse-box-typechecker/tree/test
```"fuse-box-typechecker": "git://github.com/vegarringdal/fuse-box-typechecker#test"```

I really need to try and clean up the entire plugin too when I got it working with v 1.4.1

**Comment by vegarringdal** [comment]
@nchanged pushed the newest one, noone uses the old anyways :-)
Ill have a new look on improving it more when I have better time/u go for v 2.0.0 :-)

**Comment by nchanged** [comment]
good stuff @vegarringdal i am working hard on the docs, should be there very soooon.
